import { MigrationInterface, QueryRunner } from 'typeorm';
import billers from '@database/data/billers';
import { Biller } from '@models/08-2022';

export class InitialSeeder1659677822443 implements MigrationInterface {
  name = 'InitialSeeder1659677822443';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.startTransaction();
    const billerSeeder = billers.map(b => {
      const biller = new Biller();
      // biller.id = s.id; // ID is autogenerated, won't be saved by typeorm
      biller.name = b.name;
      biller.tag = b.tag;
      return queryRunner.manager.save(biller);
    });

    await Promise.all([...billerSeeder]);
    await queryRunner.commitTransaction();
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // truncate table?
  }
}
